### ISSUE TITLE
Missing dependency spacoreforge

### ISSUE THREAD

**Issue by klangg** [heldplayer/MystNEI-Plugin#1]
When I have Forge 1.7.10-10.13.2.1291, SpACore-1.7.10-01.05.04.00, mystcraft-1.7.10-0.11.4.00, and MystNEI-Plugin-1.7.10-02.01.00.00 installed FML returns that spacoreforge could not be found.

The mcmod.info for MystNEI-Plugin requires spacore and spacoreforge. The SpACore for Forge only identifies as spacore.

**Comment by heldplayer** [comment]
Those versions aren't compatible with eachother because of some changes I made in SpACore. You're better off using an older version of SpACore with that version of MystNEI-Plugin.

**Comment by klangg** [comment]
Sorry! My fault for not making sure I had the updated version. MystNEI-Plugin-1.7.10-02.01.02.00 works fine. Thanks for the quick response.
