### ISSUE TITLE
can not go to the SSP

### ISSUE THREAD

**Issue by SvEgiiVEteR** [heldplayer/MystNEI-Plugin#6]
after updating 02.01.06.00 on 02.01.08.
entered into a single world and throws in the game menu. + game then can not close.
http://pastebin.com/0HUsem7T
java 7
forge 1492

**Comment by heldplayer** [comment]
Can you provide a crash report that was generated during the crash? This is quite the interesting crash.

EDIT: nevermind, the problem is that I'm apparently calling something that was only added in Java 8. I will bring a fix out shortly.

**Comment by heldplayer** [comment]
A new version of SpACore has been released to fix this problem. You can find it here: http://minecraft.curseforge.com/mc-mods/228922-spacore/files/2257080

Sorry for the inconvenience.

**Comment by SvEgiiVEteR** [comment]
No I can not give a crash, it is not.
the game is not broken but is no longer working world is not loaded.
working current game menu. can not leave the game .. it hangs in Task Manager when you push out of the game.
thanks but the link is empty. no file)

**Comment by heldplayer** [comment]
The file is currently under review, it's taking a bit longer than expected :/

**Comment by heldplayer** [comment]
The file has been accepted after 5 hours. Hope this fixes your issue :smile:

**Comment by SvEgiiVEteR** [comment]
yes all good) thanks)
